Introduce a checksum loop.
Best viewed with git diff/show's -b flag.

diff --git a/net-retriever b/net-retriever
--- a/net-retriever
+++ b/net-retriever
@@ -42,26 +42,28 @@ checkmatch() {
 	Release="$1"
 	Packages="$2"
 	pkgfile="$3"
-	pkgmd5="$(md5sum "$Packages" | cut -d' ' -f1)"
 	pkgsize="$(wc -c < "$Packages" | tr -d ' ')"
 
-	set -e
-	sed -n '/^MD5Sum:$/ b LOOP; b; : PRINT; /:$/q; p; : LOOP; n; b PRINT' \
-	       "$Release" | (
-		while read md5 size file; do
-			if [ "$file" = "$pkgfile" ]; then
-				if [ "$md5" != "$pkgmd5" ]; then
-					error "MD5 mismatch for $pkgfile ($md5 != $pkgmd5)."
+	for checksumtype in MD5Sum; do
+		pkgmd5=$(get_checksum "$checksumtype" "$Packages")
+		set -e
+		sed -n '/^MD5Sum:$/ b LOOP; b; : PRINT; /:$/q; p; : LOOP; n; b PRINT' \
+		       "$Release" | (
+			while read md5 size file; do
+				if [ "$file" = "$pkgfile" ]; then
+					if [ "$md5" != "$pkgmd5" ]; then
+						error "MD5 mismatch for $pkgfile ($md5 != $pkgmd5)."
+					fi
+					if [ "$size" != "$pkgsize" ]; then
+						error "Size mismatch for $pkgfile ($size != $pkgsize)."
+					fi
+					return 0
 				fi
-				if [ "$size" != "$pkgsize" ]; then
-					error "Size mismatch for $pkgfile ($size != $pkgsize)."
-				fi
-				return 0
-			fi
-		done
-		error "$pkgfile not found in $Release."
-	)
-	set +e
+			done
+			error "$pkgfile not found in $Release."
+		)
+		set +e
+	done
 }
 
 read_gpg_status() {
